modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/AxDevv/Magic-Construction/issues"

[[mods]]
modId = "magicconstruction"
version = "${file.jarVersion}"
displayName = "Magic Construction"
displayURL = "https://github.com/AxDevv/Magic-Construction"
logoFile = "logo.png"
authors = "Ax_Dev"
description = '''Building wands to place multiple blocks at once with Block Pouches and Repair Runes!'''

[[dependencies.magicconstruction]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magicconstruction]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
